# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://FANHIDE.github.io
baseurl: /
title: Yunfan Zhang
author: Yunfan Zhang
description: Personal blog and resume
avatar: profile.png
email: hideleah@email.com
github: hide # username
#Comment out if you don't want disqus
disqus: username


# needed for travis-ci build
exclude: [vendor]
